config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # test class method
  get '/tasks/show_tasks_by_user/'=> 'tasks#tasks_by_user'  
  
  #GET RID OF THIS LATER!!!!
  get '/tasks/almost_done'=> 'tasks#almost_done'

  # Sessions
    #Facebook Omniauth login
  get '/auth/facebook/callback' => 'sessions#fblogin'
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/admin/projects/:id/next', to: 'admin/projects#next'
  get '/admin/projects/:id/previous', to: 'admin/projects#previous'

  #Projects
  resources :projects, only: [:show] do 
    resources :tasks, only: [:index]
  end


  #Tasks
  resources :tasks, only: [:new, :create, :edit, :update, :show]

  #Users nested
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :tasks, only: [:new, :create, :index, :show, :edit, :update]
    resources :projects, only: [:show, :index]
  end

  # Admin tasks
  namespace :admin do
    resources :users do 
      resources :tasks, only: [:index]
      resources :projects, only: [:show]
    end
    resources :projects do 
      resources :tasks, only: [:index]
    end
    resources :tasks
  end


end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :title, presence: true

  def self.by_user(user_id, project_id)
    where(user: user_id, project: project_id)
  end

  def self.almost_done
    where("percent_complete > ?", 50)
  end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
  before_action :authentication_as_admin_required
  layout "admin"

  def index
    set_tasks

    respond_to do |f|
      f.html {render :index}
      f.json { render json: @tasks }
    end
  end

  def show
    @task = Task.find(params[:id])

    respond_to do |f|
      f.html {render :show}
      f.json { render json: @task }
    end
    
  end

  def new
    @task = Task.new(project_id: params[:project_id], user_id: params[:user_id])
    
  end

  def create
    @task = Task.create(task_params)

    # When creating tasks, need to ensure that it is added to the user's project if it already exists, otherwise add the project to user's project list.

    if !@task.save
      gather_errors(@task)

      render :new
    else
      flash[:success] = "You have successfully created a task titled, #{@task.title}."

      render json: @task, status: 201
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    @task.update(task_params)

    redirect_to admin_task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to admin_projects_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :percent_complete, :project_id, :user_id)
  end

  def set_tasks
    if !!params[:project_id]
      @tasks = Project.find(params[:project_id]).tasks
    else
      @tasks = Task.all
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout "user"
  before_action :authentication_required
  skip_before_action :authentication_required, only: [:tasks_by_user]

  def index
    if params[:user_id]
      @tasks = User.find(params[:user_id]).tasks
    else
      @tasks = Task.all
    end    
  end

  def show
    @task = Task.find(params[:id])
    
  end

  def new
    @task = Task.new
    
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if !@task.save
      gather_errors(@task)

      render :new
    else
      flash[:success] = "You have successfully created a task titled, #{@task.title}."

      redirect_to project_path(@task.project)
    end
  end

  def edit
    @task = Task.find(params[:id])
    
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def tasks_by_user

    @user = User.find(2)
    @project = @user.projects.first

    render :layout => false
    
  end

  def almost_done    
    @tasks = Task.almost_done

    render :almost_done
    
  end

  private

  def task_params
    params.require(:task).permit(:title, :content, :percent_complete, :project_id, :user_id)
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/tasks/_form.html.erb
<%= form_for task, url: path, html:{class:"new_user", id: "new_user"} do |f| %>
  <div class="form-group">
    <p><%= f.label :project_id, "Assign to Project: " %>
    <%= f.collection_select :project_id, Project.all, :id, :name %></p>
  </div>

  <div class="form-group">
  <%= f.label :user_id, "Assignee: " %>
    <%= f.collection_select :user_id, User.all, :id, :username %>
  </div>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, placeholder: "Enter a title", class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, placeholder: "Task details", class:"form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :percent_complete %><br>
    <%= f.text_field :percent_complete, placeholder: "Enter a number 1-100", class:"form-control"%>
  </div>

  <%= f.submit %><br>
<% end %>

app/views/admin/tasks/_task.html.erb
<tr>
  <td><%= link_to task.title, admin_task_path(task) %></td>
  <% if !params[:user_id] %>
    <td><%= task.user.username %> (<a href="
      mailto: <%= task.user.email %>">email</a>)</td>
  <% end %>
  <td><%= task.percent_complete %></td>
  <td><%= link_to "Edit", edit_admin_task_path(task) %></td>
  <td><%= link_to task.project.name, admin_project_path(task.project) %></td>
</tr>

app/views/admin/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render partial: "form", locals: {task: @task, path: admin_task_path} %>

app/views/admin/tasks/index.html.erb
<h1>All Tasks | <%= link_to "Add a Task", new_admin_task_path %></h1> 

<% if @tasks.empty? %>
  <p>There are no tasks to show</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Task Name</th>
        <th>Assignee</th>
        <th>Percent Complete</th>
        <th>Action</th>
        <th>Project</th>
      </tr>
    </thead>
    <tbody>
      <p><%= render(@tasks) %></p>
    </tbody>
  </table>
<% end %>

app/views/admin/tasks/new.html.erb
<h1>Create New Task</h1>
<%= render partial: "form", locals: {task: @task, path: admin_tasks_path} %>

app/views/admin/tasks/show.html.erb
<h1>Task: <%= @task.title %></h1>

<h3>For project: <%= link_to @task.project.name, admin_project_path(@task.project) %></h3>
<h3>Assigned user: <%= @task.user.username %></h3>

<h3>Task details:</h3>
<p><%= @task.content %></p>

<h3> Completion status:</h3>
<p><%= @task.percent_complete %>%</p>

<!-- Edit TASK -->
<h4></h4>

<!-- Delete Task -->
<%= form_for @task, url: admin_task_path, method: :delete do |f| %>
  <%= f.submit "Delete task" %> | <%= link_to "Edit task", edit_admin_task_path(@task) %><br/>
<% end %>