config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # test class method
  get '/tasks/show_tasks_by_user/'=> 'tasks#tasks_by_user'  
  
  #GET RID OF THIS LATER!!!!
  get '/tasks/almost_done'=> 'tasks#almost_done'

  # Sessions
    #Facebook Omniauth login
  get '/auth/facebook/callback' => 'sessions#fblogin'
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/admin/projects/:id/next', to: 'admin/projects#next'
  get '/admin/projects/:id/previous', to: 'admin/projects#previous'

  #Projects
  resources :projects, only: [:show] do 
    resources :tasks, only: [:index]
  end


  #Tasks
  resources :tasks, only: [:new, :create, :edit, :update, :show]

  #Users nested
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :tasks, only: [:new, :create, :index, :show, :edit, :update]
    resources :projects, only: [:show, :index]
  end

  # Admin tasks
  namespace :admin do
    resources :users do 
      resources :tasks, only: [:index]
      resources :projects, only: [:show]
    end
    resources :projects do 
      resources :tasks, only: [:index]
    end
    resources :tasks
  end


end

app/models/user.rb
class User < ApplicationRecord
  #associations
  has_many :tasks
  has_many :projects, through: :tasks
  
  #bcrypt
  has_secure_password

  # validations
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true

  accepts_nested_attributes_for :projects

  def is_admin?
    self.admin == 1
  end

  def all_user_tasks
    Task.where("user_id = ?", self.id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authentication_as_admin_required
  layout "admin"

  def index
    @users = User.all
    respond_to do |f|
      f.html {render :index}
      f.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |f|
      f.html {render :show}
      f.json { render json: @user }
    end
    
  end

  def create
    binding.pry
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "You have successfully created a new user, #{@user.username}."

      redirect_to admin_users_path      
    else
      gather_errors(@user)

      render :new
    end
  end

  def new
    @user = User.new
    
  end

  def edit
    @user = User.find(params[:id])
    
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to admin_user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.tasks.destroy_all

    @user.destroy
    flash[:success] = "You have successfully deleted the user, #{@user.username}."
    
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :admin,
      project_ids:[],
      projects_attributes:[:name, :deadline]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "user", except: [:new, :create]
  before_action :authentication_required
  skip_before_action :authentication_required, only: [:new, :create]  

  def index
    @users = User.all
    
  end

  def show
    @user = User.find(current_user.id)
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "You have successfully created a new user, #{@user.username}."
      session[:user_id] = @user.id
      
      redirect_to user_path(@user)      
    else
      gather_errors(@user)

      render :"/users/new"
    end
  end

  def new
    @user = User.new
    render :layout => "application"
    
  end

  def edit
    @user = User.find(params[:id])
    
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:id])
    @user.all_user_tasks.destroy_all

    @user.destroy

    redirect_to projects_path
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :email,
      :password,
      :admin,
      project_ids:[],
      projects_attributes:[:name, :deadline]
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for user, html:{class:"new_user", id: "new_user"} do |f| %>

<!-- Username -->
  <div class="form-group">
    <%= f.label :username%><br>
    <%= f.text_field :username, placeholder: "Enter username", class:"form-control"%>
  </div>
<!-- Email -->
  <div class="form-group">
    <%= f.label :email%><br>
    <%= f.text_field :email, placeholder: "Enter email address", class:"form-control"%>
  </div>
<!-- Password -->
  <div class="form-group">
    <%= f.label :password, "Enter password" %><br>
    <%= f.password_field :password, placeholder: "Enter password", class:"form-control"%>
  </div>

  <%= f.submit %><br>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.username %></td>
  <% if !user.email.blank? %>
    <td><a href="mailto:<%= user.email %>"><%= user.email %></a></td>
  <% else %>
    <td>No contact info provided</td>
  <% end %>
    <td><%= user.tasks.count %></td>
    <% if current_user.is_admin? %>
      <td><%= link_to "Show", user_path(user) %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
    <% end %>
</tr>

app/views/users/new.html.erb
  <h1>Create New User</h1>

  <%= form_for @user, html:{class:"new_user", id: "new_user"} do |f| %>

<!-- Username -->
  <div class="form-group">
    <%= f.label :username%><br>
    <%= f.text_field :username, placeholder: "Enter username", class:"form-control"%>
  </div>
<!-- Email -->
  <div class="form-group">
    <%= f.label :email%><br>
    <%= f.text_field :email, placeholder: "Enter email address", class:"form-control"%>
  </div>
<!-- Password -->
  <div class="form-group">
    <%= f.label :password, "Enter password" %><br>
    <%= f.password_field :password, placeholder: "Enter password", class:"form-control"%>
  </div>

  <!-- Admin? -->
  <div class="form-group">
    <%= f.label :admin, "Are you an administrator? " %>
    <%= f.check_box :admin%>
  </div>

  <%= f.submit %><br>
<% end %>

app/views/users/show.html.erb
<h1>Dashboard | <%= link_to "Edit profile", edit_user_path(@user) %>
<h3>Username: <%= @user.username %></h3>
<h3>Email: <a href="mailto: <%= @user.email %>"><%= @user.email %></a></h3>
<h3>Todo:</h3>
<h4>You have <%= @user.tasks.count %> task(s) outstanding | <%= link_to "View your tasks", user_tasks_path(@user.id) %></h4>
<br>

<!-- Show project list-->
<h4>Your Project List: </h4>
<% if @user.projects.empty? %>
  <p>There are currently no projects to show</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Project Name</th>
        <th>Due Date</th>
        <th>Details</th>
      </tr>
    </thead>
    <tbody>
      <p><% @user.projects.uniq.each do |project| %></p>
      <tr>
        <td><%= project.name %></td>
        <td><%= nice_date_format project if project.name != "Unsorted" %></td>
        <td><%= link_to "Show", user_project_path(@user, project) %></td>
      <% end %>
      </tr>
    </tbody>
  </table>
<% end %>