config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  # test class method
  get '/tasks/show_tasks_by_user/'=> 'tasks#tasks_by_user'  
  
  #GET RID OF THIS LATER!!!!
  get '/tasks/almost_done'=> 'tasks#almost_done'

  # Sessions
    #Facebook Omniauth login
  get '/auth/facebook/callback' => 'sessions#fblogin'
  get '/login' => "sessions#new"
  post '/sessions' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/admin/projects/:id/next', to: 'admin/projects#next'
  get '/admin/projects/:id/previous', to: 'admin/projects#previous'

  #Projects
  resources :projects, only: [:show] do 
    resources :tasks, only: [:index]
  end


  #Tasks
  resources :tasks, only: [:new, :create, :edit, :update, :show]

  #Users nested
  resources :users, only: [:new, :create, :show, :edit, :update] do
    resources :tasks, only: [:new, :create, :index, :show, :edit, :update]
    resources :projects, only: [:show, :index]
  end

  # Admin tasks
  namespace :admin do
    resources :users do 
      resources :tasks, only: [:index]
      resources :projects, only: [:show]
    end
    resources :projects do 
      resources :tasks, only: [:index]
    end
    resources :tasks
  end


end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagerV002</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>


  <!-- template for Navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Projects Dashboard", admin_projects_path, class: "navbar-brand all_projects" %>
          <%= link_to "All Users", admin_users_path, class: "navbar-brand" %>
          <%= link_to "All Tasks", admin_tasks_path, class: "navbar-brand" %>          
          <% if !Project.all.empty? %>
            <%= link_to "Create Task", new_admin_task_path, class: "navbar-brand" %>
          <% end %>
          <%= link_to "Create User", new_admin_user_path, class: "navbar-brand" %>
          <%= link_to "Create Project", new_admin_project_path, class: "navbar-brand" %> 
          <%= link_to "Logout", logout_path, class: "navbar-brand" %>
        </div>
      </div>
    </div>
    <div class="center">
      <!-- <div class="info"> -->
        <div class="container">
          <h2>You are logged in as an Administrator</h2>
          <!-- show error messages if any -->
          <% flash.each do |key, value| %>
            <% if value.class == Array %>
              <% value.each do |message|%>
                <%= content_tag :div, message %>
              <% end%>
            <% else %>
              <%= content_tag :div, value, class: "flash #{key}" %>
            <% end %>
            <% end %> <!-- flash errors end -->
            <div id="app-container">
              <%= yield %>
            </div>
        </div>
      <!-- </div> -->
    </div>
  <!-- Footer template -->
    <footer class="center">
        <h5>Helpful Research Resources:</h5>
        <a href="http://wikipedia.org" >Wikipedia</a><br>
        <a href="http://google.com" >Google it!</a><br>
        <a href="mailto: support@systems.com">Email Support</a>
    </footer>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagerV002</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <!-- template for Navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
            <%= link_to "Signup", new_user_path, class: "navbar-brand" %>
            <%= link_to "Login", login_path, class: "navbar-brand" %>
            
          </div>
      </div>
    </div>
    <div class="center">
      <!-- <div class="info"> -->
        <div class="container">
        <!-- show error messages if any -->
        <% flash.each do |key, value| %>
          <% if value.class == Array %>
            <% value.each do |message|%>
              <%= content_tag :div, message %>
            <% end%>
          <% else %>
            <%= content_tag :div, value, class: "flash #{key}" %>
          <% end %>
        <% end %> <!-- flash errors end -->
        <%= yield %>
        </div>
      <!-- </div> -->
    </div>

  </body>

  <!-- Footer template -->
  <footer class="center">
		<p>Helpful Research Resources:<br>
			<a href="http://wikipedia.org" >Wikipedia</a><br>
			<a href="http://google.com" >Google it!</a><br>
			<a href="mailto: support@systems.com">Email Support</a>
		</p>
	</footer>

</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagerV001</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>


  <!-- template for Navbar NOT LOGGED IN-->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          
        </div>
      </div>
    </div>
    <div class="center">
      <!-- <div class="info"> -->
        <div class="container">
        <!-- show error messages if any -->
        <% flash.each do |key, value| %>
          <% if value.class == Array %>
            <% value.each do |message|%>
              <%= content_tag :div, message %>
            <% end%>
          <% else %>
            <%= content_tag :div, value, class: "flash #{key}" %>
          <% end %>
        <% end %> <!-- flash errors end -->
        
        <%= yield %>
        </div>
      <!-- </div> -->
    </div>

  </body>

  <!-- Footer template -->
  <footer class="center">
		<p>Helpful Research Resources:<br>
			<a href="http://wikipedia.org" >Wikipedia</a><br>
			<a href="http://google.com" >Google it!</a><br>
			<a href="mailto: support@systems.com">Email Support</a>
		</p>
	</footer>

</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagerV001</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>


  <!-- template for Navbar NOT LOGGED IN-->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Dashboard", user_path(current_user), class: "navbar-brand" %>
          <%= link_to "Your Tasks", user_tasks_path(current_user), class: "navbar-brand" %>          
          <%= link_to "Create Task", new_user_task_path(current_user), class: "navbar-brand" if !current_user.projects.empty? %>

          <%= link_to "Logout", logout_path, class: "navbar-brand" %>
        </div>
      </div>
    </div>
    <div class="center">
      <!-- <div class="info"> -->
        <div class="container">
        <!-- show error messages if any -->
        <% flash.each do |key, value| %>
          <% if value.class == Array %>
            <% value.each do |message|%>
              <%= content_tag :div, message %>
            <% end%>
          <% else %>
            <%= content_tag :div, value, class: "flash #{key}" %>
          <% end %>
        <% end %> <!-- flash errors end -->
        
        <%= yield %>
        </div>
      <!-- </div> -->
    </div>

  </body>

  <!-- Footer template -->
  <footer class="center">
		<p>Helpful Research Resources:<br>
			<a href="http://wikipedia.org" >Wikipedia</a><br>
			<a href="http://google.com" >Google it!</a><br>
			<a href="mailto: support@systems.com">Email Support</a>
		</p>
	</footer>

</html>